apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-${TARGET_ROLE}
spec:
  selector:
    matchLabels:
      app: gateway

  template:
    metadata:
      labels:
        app: gateway
        role: ${TARGET_ROLE}

    spec:
      containers:
      - name: ${GATEWAY_IMAGE_NAME}
        image: "${ACR_REGISTRY}/${GATEWAY_IMAGE_NAME}:${IMAGE_TAG}"
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: admin
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: admin
          - name: STATISTICS_SERVICE_PASSWORD
            value: admin
          - name: ACCOUNT_SERVICE_PASSWORD
            value: admin
          - name: MONGODB_CONNECTION_STRING
            value: mongodb://piggy:nSpeYPy89Fs2KPSBe4ACXhaTOjnABHPqWCcufY4sPfD6NYDXNSaRGW9dZ8I8BBsx1oGU5IEI58EPEOTj4FjnJg==@piggy.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: "${ACR_SECRET}"
